### ISSUE TITLE
Does the campaign still want people using this?

### ISSUE THREAD

**Issue by ccallahan** [Bernie-2016/SignupApp#1]
I would love to use this at events ran by me, but is it still in use by the campaign or is it depriciated?

**Comment by schneidmaster** [comment]
This app is designed specifically for campaign chromebooks. The recommended means of collecting signups for your events is through Bernie QR. First, you download the smartphone app on your [iOS](https://itunes.apple.com/us/app/bernie-qr/id1047331796?mt=8) or [Android](https://play.google.com/store/apps/details?id=com.berniesanders.signup_qr_scanner) device. Then, you direct your guests to visit http://bernie.to/qr (or https://bernietickets.com) and fill out the signup form. That gives the guests a QR code, which you scan using the QR app to collect the signup. Hope this helps!
